### ISSUE TITLE
Moving Items between ArraySchemas issues

### ISSUE THREAD

**Issue by Zielak** [colyseus/colyseus.js#53] opened 2019-06-13 06:31 UTC
I have an issue with moving items between ArraySchemas in my project. Client-side has issues getting all the values of the item and just fills them with `undefined`. 

I modified `colyseus-examples` to reproduce it and its worse, I get more errors on the client: https://github.com/Zielak/colyseus-examples (in 02-state-handler):
- addItem - button adds new Item to current player
- moveItem - moves one item from current player to some other random player

On the first "moveItem" I get this error in browser:

```
Uncaught TypeError: Cannot read property '_schema' of undefined
    at colyseus.js:1
    at t.e.decode (colyseus.js:1)
    at colyseus.js:1
    at t.e.decode (colyseus.js:1)
    at e.patch (colyseus.js:1)
    at e.patch (colyseus.js:1)
    at e.onMessageCallback (colyseus.js:1)
    at t.value (colyseus.js:1)
```

Here's what I do on server-side:
```
// Pick an item
const item = this.players[id].items[itemIdx];

// Remove that item from myself
this.players[id].items.splice(itemIdx, 1);

// Add it to the other player
targetPlayer.items.push(item);
```

and the changes on server-side are all there, I explore the state and all the items are in the correct position after "moving", and with correct values.

I added tests on colyseus/schema with the same use case and the tests pass:
https://github.com/Zielak/schema/commit/c2c2eabd2f5e72dd3b92c44ba22ae0a6ecf95f40

**Comment by Zielak** [comment] 2019-06-17 15:06
Just an update on what I found while debugging Colyseus. Here's the case:
- I'm listening for `onStateChange` room event
- I'm moving one item, a playing card, to different ArrayScheme
- It's got properties like: x, y, angle, idx, suit and rank. ('idx' is its true position in hand)

In the browser, decoding stops after x, y, angle and idx. Thats why I have a bunch of `undefined` values for this card.

On server side, at the moment of encoding this one card, I can see that Colyseus choses to encode only properties saved in `$changes.changes`, which contains only x, y, angle and idx.
```javascript
// Schema.ts:509
const keys = (encodeAll || client)
    ? value.$changes.allChanges
    : value.$changes.changes;
```

Which kinda makes sense, because while moving this card to another container:
- it's position changes - x, y
- it's angle changes - cards are rotated differently when in hand or on the pile of cards)
- it's idx changes - in my case, I choose 8th card in my hand to be moved to empty container, so its new `idx` becomes `0`

The name, suit and rank don't actually change, it's still 8 of hearts.

I don't feel confident enough with Colyseus codebase to try my own fix, but hopefully you'll find some use in my investigation. 🤗

**Comment by endel** [comment] 2019-06-17 15:09
Thanks for your further inspection @Zielak, I'll investigate this tonight so tomorrow we'll probably have a fix for this! Cheers!

**Comment by endel** [comment] 2019-06-18 02:59
I've had some progress inspecting this today, added a failing test-case moving 4 items back and forth between arrays, and after a couple of moves, all items wrongly encoded. https://github.com/colyseus/schema/commit/1b48ef3734156e48901c0b7390ee1ec498ea7531

I'll continue inspecting tomorrow!

**Comment by shunia** [comment] 2019-06-21 09:49
Found it might be caused by the client library.

After cloned this repo, I tried these:
1. Build in webpack's develop mode;
2. Upgrade webpack to version 4 and all it's plugins to the right version, then build in webpack's production mode;

**either** works and no `'_schema'` error logged anymore.

**Comment by Zielak** [comment] 2019-07-14 13:29
I spend more time investigating, and I think I got more precise test cases, ready in PR: https://github.com/colyseus/schema/pull/29

So for me, the issue is mainly happening when I try to move an item, which is "in the middle" of ArraySchema. "Moving" top-most item works fine. Here's step-by-step what happens in my game, when I'm moving items around:
- an Item is changing parents, so I'm first removing it from its current parent with `splice()` method.
- I'm calling `updateIndexes()` on that parent container, so its remaining child items get their `idx` numbers updated. Example, only 2 items require an update:

|  | indexes |
| --- | --- |
| before | 0, 1, 2, 3 |
| removing item `1` | 0, **2, 3** |
| updateIdx() | 0, **1, 2** |

After that I'm pushing this item to its new parent, but here is where it breaks in the tests I wrote for Schema lib. After splicing and changing a prop in some items, the encoded/decoded state doesn't preserve these changed props.

I wrote 2 tests:
- one, simulating the above scenario (splice one item, update indexes for the rest)
- second, simpler: splice one item, change name of another one.

**Comment by endel** [comment] 2019-08-24 15:01
Can we close this @Zielak? 👀

**Comment by Zielak** [comment] 2019-08-24 19:21
Yes we can!

**Closed** 2019-08-24 19:21 UTC
Labels: @colyseus/schema
